### ISSUE TITLE
Can't specify a specific migration when running a down command

### ISSUE THREAD

**Issue by toymachiner62** [db-migrate/node-db-migrate#222]
I'm trying to run the down command for a specific migration file and it doesn't seem to be working:

```sh
$ db-migrate down 20150211213723-add-activities -e undefined 
[INFO] Ignoring migration name for down migrations.  Use --count to control how many down migrations are run.
[INFO] Defaulting to running 1 down migration.
[INFO] Processed migration 20150211210228-add-tokens
[INFO] Done
```

**Comment by wzrdtales** [comment]
I see, the docs are misleading again.

    db-migrate [up|down|create] migrationName [options]

The migrationName is referenced to the create method, but not to down or up. That's probably a feature to add.

Questionable if it's not dangerous running migrations out of order.

**Comment by toymachiner62** [comment]
I suppose it does give the user the opportunity to be dangerous, but i see that the rails migration lib allows this so it must not be too dangerous right? :) http://edgeguides.rubyonrails.org/active_record_migrations.html#running-specific-migrations

**Comment by wzrdtales** [comment]
Saying you are able to jump off the cliff doesn't makes it less dangerous ;)

**Comment by toymachiner62** [comment]
Ha that's true. I still think it's a feature that should be added. What if i create 3 migrations and then run all 3 of them. Then i decide I didn't need the second one. There's no way to "down" that one so I have to manually delete the migration file + manually undo whatever that migration just did in the database.

**Comment by wzrdtales** [comment]
Well you could also chain 3 commands, down/reset && rm file && up ;)

But it wont hurt to implement it, also I still can't see the advantage. But thats just my view of the things.

**Comment by wzrdtales** [comment]
I always think of this as probably dangerous. You have 3 migrations and you want to delete one. Then I might ask, why do you want this? Because it's not shared over the repository or in production? Well that would be legible, but what if you just miss something, down this single migration and now one hour later something doesn't work like you expect it to work.

You now waste a half hour to track down the bug, just to realize you've invaldited your database. That would be a worst case scenario that could happen with this.

I might be a bit pedantic and always want control over the things I'm doing, that is also the reason why I count on the mind and ideas of the community, too. I'm still suspicious about it, but try to make things fit ;)

**Comment by wzrdtales** [comment]
@toymachiner62 
Support for specifying also in a down migration is now being added, but not just the single migration, but that migration being the target up to which it will migrate down. Also to note, this is used as target, that means the target itself wont be executed itself.
