### ISSUE TITLE
can't connect to rds database - possibly incorrect database.json file

### ISSUE THREAD

**Issue by pedalpete** [db-migrate/node-db-migrate#252]
Not sure what I'm doing wrong here, but I keep getting an error 
`Error: getaddrinfo ENOTFOUND [rds.server.address]`
I've been trying to look through your documentation and code to find how the database.json should be structured, and I've tried to follow what I've found. 

My database.json file is (password and addresses have been changed)

```
{
    "dev": {
        "url": "postgres://USER:PASS@ENDPOINT_ADDRESS:PORT/DB_NAME",
        "host": "ENDPOINT_WITH:PORT",
        "user": "USER",
        "password": "PASSWORD",
        "database":"DB_NAME",
        "schema": "public",
        "driver": "pg"
    }
}
```

I've tried looking through the documentation of parse-database-url as well, but no documentation there is pointing to the issue either. 

Going through the config.js file, I can see that the database.json seems to be parsed correctly, but it just refuses to get a connection. 
##

**Comment by wzrdtales** [comment]
You should whether use url or host,user,password,database but not both.

See this for an example configuration:
http://db-migrate.readthedocs.org/en/v0.9.x/Getting%20Started/configuration/

**Comment by pedalpete** [comment]
thanks wzrdtales, you are correct that trying both url and host results in some... strange behaviour. 
What I'm seeing is that if I use `host, user, password, database`, the connection object is correct, but the `getaddrinfo` error, which I've been unable to pin down. 

If I use URL, the object that gets passed to `pg.connect` is my localhost details, so it appears url is not being picked up at all. If I use just a string, the string is parsed into the correct database object, but I still get the `getaddrinfo` error. 

I'm using the same database configuration in a kraken.js app also connecting through pg, and that connects without issue. I've been trying to debug what's going wrong, or why it would be different with db-migrate, but it shouldn't be. 

I've decided to fork db-migrate and see if I can get that working with kraken, so I can use the kraken config. That may point out the issue, in which case I'll post back here. 

Thanks for your help.

**Comment by wzrdtales** [comment]
Thank you for investigating on this, if you need any further help don't hesitate to ask.

**Comment by wzrdtales** [comment]
@pedalpete **To note**: If you discover the root of your issue and a solution to it, I would appreciate if you would open a pull request to https://github.com/db-migrate/english-docs and document this.

Thank you

**Comment by wzrdtales** [comment]
@pedalpete any progress on this?

**Comment by ecksun** [comment]
I don't know if its related but I'm having similar issues.

    $ ./node_modules/.bin/db-migrate --env staging --dry-run --verbose --config config/database.json up
    [INFO] dry run
    [INFO] Using staging settings: { driver: 'pg',
      host: 'localhost:5433',
      port: '5433',
      database: 'adatabase',
      user: 'auser',
      password: '******' }
    [INFO] require: ./pg
    [INFO] connecting
    [INFO] connected
    [SQL] select version() as version
    select version() as version
    [ERROR] Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:124:16)

I was debugging it some and noticed that `index.connect` in `executeUp` works
fine but some time after calling `migrator.driver.createMigrationsTable` the
issue arises

Setting a breakpoint in dns.js (`sb('dns.js', 37)`) showed that the host it
couldn't resolve was `localhost:5433`, which seems to suggest the issue is
related to specyfing the port.

**Comment by wzrdtales** [comment]
```
host: 'localhost:5433',
  port: '5433',
```

Why do you specify the port twice?

**Comment by wzrdtales** [comment]
@ecksun This is possibly your issue, the host is only the host. The way you defined your configuration applies to connection strings, but in this case you're using parameters.

Also take look at the parameter list of pg.
https://github.com/brianc/node-postgres/wiki/Client#new-clientobject-config--client

So just config like the following:

* host: this is only the hostname/domain/ip
* port: here you specify your port

**Comment by ecksun** [comment]
The port field was added later when I started to try to find a workaround to the issue, before I only had specified the host field ("localhost:5433").

I never realized that the parameter list is just passed through to node-postgres, I don't know if it's because I missed that part of the documentation or if its simply missing but I do think it might be something we could improve upon.

**Comment by wzrdtales** [comment]
I'm always open to improve our documentation though :)

Does it works now for you or do you still have issues?

**Comment by ecksun** [comment]
Yes, it works when I specify the port separately.

I would suggest you quickly write about how the config parameters are used and
what they are in the
[configuration](https://github.com/db-migrate/node-db-migrate/#configuration
section).

And if it is so that the configs are only passed through, just mentioning that
should be more than good enough (doesnt have to be more than a sentence
really).

I would send a PR if I knew better how the configs were dealt with :(

**Comment by wzrdtales** [comment]
Ok perfect, I guess I will rewrite this documentation part and separate simple examples and structurize the in depth configurations.
