### ISSUE TITLE
Export SQL for all migrations

### ISSUE THREAD

**Issue by IyadAssaf** [db-migrate/node-db-migrate#280]
I think it would be useful to export the raw SQL commands from all of the migrations so it can be used to initialise new databases from a single file. 

For example in my testing environment I generate and start a local Postgres instance which requires setup via migrations before any tests can be run. Currently I have to store ~50 migration files in my repo and run these on every test run. In my case, it would be beneficial from an organisational standpoint to only have one file of SQL to initialise it. 

In practise, the command might look like this (--all to run all migrations, --sql-out to print to stdout):
`db-migrate up --all --sql-out > allMigrations.sql`

Thoughts? I would imagine such a feature may be useful for a few others.

**Comment by zyberspace** [comment]
What about dumping the structure together with the complete `migrations`-table? (from command line)
You could then include this sql-file into your project and use it when you set up a new environment.

When you then run `db-migrate up`, it will look into the `migrations`-table and say "No migrations to run".

Would be nice to have a build-in-function for this tho. :+1:

**Comment by wzrdtales** [comment]
I think the proper way would be, to add a log level specification:

    db-migrate up --dry-run --log-level sql > migrations.sql

and a --ignore-completed-migrations flag

Thoghts?

**Comment by wzrdtales** [comment]
Would look like the following if implemented like suggested:

```sql
[tobi@tobi:node-db-migrate master*]$ bin/db-migrate up --dry-run --ignore-completed-migrations --log-level sql
CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150220133929-test6', '2015-06-28 13:18:57' ] ]
COMMIT;
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150302131335-test1', '2015-06-28 13:18:57' ] ]
COMMIT;
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150302131336-test2', '2015-06-28 13:18:57' ] ]
COMMIT;
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150302131338-test3', '2015-06-28 13:18:57' ] ]
COMMIT;
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150305131350-test4', '2015-06-28 13:18:57' ] ]
COMMIT;
SET AUTOCOMMIT=0;
START TRANSACTION;
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20150330121354-test5', '2015-06-28 13:18:57' ] ]
COMMIT;
```

**Comment by wzrdtales** [comment]
Example implementation:

```sql
[tobi@tobi:node-db-migrate master*]$ bin/db-migrate up --dry-run --ignore-completed-migrations --non-transactional --log-level sql
CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150220133929-test6", "2015-06-28 13:52:38")
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150302131335-test1", "2015-06-28 13:52:38")
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150302131336-test2", "2015-06-28 13:52:38")
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150302131338-test3", "2015-06-28 13:52:38")
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150305131350-test4", "2015-06-28 13:52:38")
INSERT INTO `migrations` (`name`, `run_on`) VALUES ("/20150330121354-test5", "2015-06-28 13:52:38")
```

**Comment by wzrdtales** [comment]
Pushed example implementation to https://github.com/db-migrate/node-db-migrate/tree/exportSQLMigrations

**Comment by zyberspace** [comment]
@wzrdtales But then it would still run all migrations, you would just have them collected in one file.
I think what @IyadAssaf wanted to have, is a way to create the tables for a new database, for example if you are a new developer and just cloned the project.

```shell
> git clone git.myserver.tld:myproject.git
> cd myproject
> db-migrate init
Initiating database...
  CREATE TABLE users....
```

`db-migrate init` could for example take a `structure.sql` (as stated above) as source. If then some changes get made with `db-migrate create`,it would not only create the `.js`-file but also update the `structure.sql`.

**Comment by wzrdtales** [comment]
No I think this is exactly what he wants, because this was exactly what he has written:
 > I think it would be useful to export the raw SQL commands from all of the migrations so it can be used to initialise new databases from a single file.

If we talk about *dumping* a database, you're in the wrong project :)

There is another project of me https://github.com/wzrdtales/node-ultimate-migrate, which reverts existing database schemas to migrations and also delivers the ability to make diffs against existing databases and the actual existing migrations to remove the need to write migrations by hand if they already exist in the current schema.

I don't see the sense in this structure.sql, I think you want to have a file that got the table schema already applied without running through the migrations and altering the table multliple times?
That is something we can think of, but we would need a good concept to realize this.

**Comment by zyberspace** [comment]
> No I think this is exactly what he wants, because this was exactly what he has written:

Damn, you are right, my bad :D

> If we talk about dumping a database, you're in the wrong project :)

Not exactly (you are the developer of course ;) ), if you don't already have a scheme to work on (/migrate), you need  to run every single migration on that database, which would be much slower than having the current structure saved somewhere and use it if there are no tables yet in the database-scheme. 
But like you said, this is then not actually an migration-task and therefore maybe not the right project but i see database-migration as a version-control for databases, which then also needs to take care about the initiation-part.

But i will maybe open a new issue for that, because, like you said, op seems just to want an option to put all migrations in one file.

**Comment by IyadAssaf** [comment]
Yep, this is exactly what I was talking about. Thanks for the quick turnaround, this is awesome!

**Comment by wzrdtales** [comment]
@zyberspace Yes please open a new issue for this :)

Closed as it is already contained in the master.
