### ISSUE TITLE
Migrations ran_on using current date

### ISSUE THREAD

**Issue by ramakrishnan** [db-migrate/node-db-migrate#295]
When I run a batch of migrations. The ran_on column takes the current date. I feel this should be the timestamp of the migration file. This will help us in rolling back the last ran migrations,

When the ran_on has the same timestamp rollback might not undo the last migration ran as ordering by ran_on may not point to the previous migration.

**Comment by wzrdtales** [comment]
@ramakrishnan This sounds more to me, as if you're manipulating the order in which you execute your migrations. As they get executed in the order of their timestamps.

Please provide a use case, when this would happen and why you think this would be a solution that would fit in more natural, then using the actual point in time, to give me an insight and make me able to make the right decision.

Thank you

**Comment by wzrdtales** [comment]
Also I don't understand your logic at this point:

> This will help us in rolling back the last ran migrations,

When you want to rollback the last ran migration, than it has to be the actual timestamp, as you might have copied over a migration from another project, which timestamp doesn't fit in.

**Comment by ramakrishnan** [comment]
@wzrdtales 
Lets say if I create two migrations.
create_customers and create_accounts, thought the file name will have different (timestamp) when ran using `db-migrate up` the migrations table's ran_on will have the same timestamp, as both these migrations got executed on the same time.

Lets assume customer got created first and accounts got created later.

Now what if I need to rollback one level down. (ie) rollback accounts. Things will be fine as long as the database returns the migrations in proper descending order. ie ` SELECT * from migrations order by ran_on desc`. 
But what if the order returns customer in the top, since its ordering on ran_on which is the same for both the records.

Is this an edge case during rollback? Also I feel the behavior could be different in different databases.

**Comment by ramakrishnan** [comment]
Any thoughts on my comments?

**Comment by wzrdtales** [comment]
Yes but the last two days I have dedicated to other projects.

Actually the sorting is like the following: https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/base.js#L473

First sorting with the run date and then with the migration date. That is perfectly fine already, as if there were executed many migrations at the same time, they would be rolled back in the same order of their names. The ordering of db-migrate and the Databases using `DESC` is identically. If there might be any database System that does handle this different, this is not a problem of db-migrate. This is something that needs to be fixed in the `allLoadedMigrations` function of the specific driver.

That means, if there is a database System out there which someone provides a driver for, it is his responsibility to return the right ordering if the db doesn't do this.

**Comment by ramakrishnan** [comment]
Thanks a lot for the clarifications. It makes sense, it boils down to the driver's implementation of handling `allLoadedMigrations`.

**Comment by wzrdtales** [comment]
No problem, if you have any other questions don't hesitate to ask.
