### ISSUE TITLE
Foreign key on creation not being added (postgres)

### ISSUE THREAD

**Issue by edorivai** [db-migrate/node-db-migrate#314]
I might be missing something, but running when the following migration on Postgres, the foreign key fails to be added:

```
var dbm = global.dbm || require('db-migrate');
var type = dbm.dataType;

const async = require('async');

exports.up = function (db, callback) {
	async.series([
		function createForeign(callback) {
			db.createTable('foreign', {
				id: {
					type         : type.INTEGER,
					unsigned     : true,
					primaryKey   : true,
					autoIncrement: true
				}
			}, callback);
		},
		function createTest(callback) {
			db.createTable('test', {
				id: {
					type         : type.INTEGER,
					unsigned     : true,
					primaryKey   : true,
					autoIncrement: true
				},
				foreignId: {
					type         : type.INTEGER,
					unsigned     : true,
					foreignKey: {
						name: 'testingForeignKey',
						table: 'foreign',
						rules: {
							onDelete: 'RESTRICT'
						},
						mapping: 'id'
					}
				}
			})
			
		}
	], callback);
	callback();
};

exports.down = function (db, callback) {
	async.each(['test', 'foreign'], function(table, callback) {
		db.dropTable(table, callback);
	}, callback);
};
```

```
$ db-migrate up -v
...
[INFO] creating table: foreign
[SQL] CREATE TABLE  "foreign" ("id"   SERIAL PRIMARY KEY)
[SQL] INSERT INTO "migrations" (name, run_on) VALUES ($1, $2) [ [ '/20151016112729-test',
    Fri Oct 16 2015 13:35:07 GMT+0200 (CEST) ] ]
[INFO] creating table: test
[SQL] CREATE TABLE  "test" ("id"   SERIAL PRIMARY KEY, "foreignId" INTEGER  )
[INFO] Processed migration 20151016112729-test
...
```

**Comment by wzrdtales** [comment]
Already answered in #237

**Comment by edorivai** [comment]
Ah, I see, thanks for the swift reply. Sorry for spamming, but is there any indication as to when the 0.10 update will come through?

**Comment by wzrdtales** [comment]
I have a lot of changes here local on my sys which I haven't pushed up yet. I'm currently finalizing everything of the seeder components. Other preparations have been done over the last few weeks (moved the drivers out of the repository).
I'm also working on another currently project, but I'm looking forward to give db-migrate a big timeslot tomorrow and finish on these things. After that there are only tests are missing, I'm going to release the first alpha version of 0.10 by then. However I took me a note so that I will give a statement tomorrow evening of how the schedule is finally planned.

**Comment by wzrdtales** [comment]
For a small overview:
https://github.com/db-migrate/node-db-migrate/milestones/v0.10.0

These items are currently still open, many of them are duplicates and others just lack of documentation and are finished themselfes.

**Comment by edorivai** [comment]
Awesome, thanks!
