### ISSUE TITLE
Running db-migrate programtically

### ISSUE THREAD

**Issue by HopefulLlama** [db-migrate/node-db-migrate#345]
I would like to be able to run db-migrate programmatically, such that all migrations run on start-up of my application.

I have tried to use the Programmable API as described, such as:

`var DbMigrate = require('db-migrate');
var dbm = DbMigrate.getInstance(true);
dbm.run();`

However, I get no such luck with this. I simply get the following error:

`[ERROR] TypeError: Cannot read property 'split' of undefined`

Any guidance would be great, thanks.

Node version: 4.2.4
NPM version: 2.14.12
db-migrate version: 0.10.0-beta.9
db-migrate-mysql version: 1.1.3
##

**Comment by wzrdtales** [comment]
May be an example project would fit for that, I will take a look at that tomorrow.

**Comment by wzrdtales** [comment]
Yesterday was no time, to give you an example right now: If you want to call the command line version you can see this as example:

https://github.com/db-migrate/node-db-migrate/blob/master/bin/db-migrate

As the db-migrate startup also utilize the same API, I will take a look today to make another example.

**Comment by HopefulLlama** [comment]
Don't worry about it! There's no rush.

This looks good and should work! I'll give it a go and let you know how it
goes. I should be able to get to it in the next couple of days.

**Comment by wzrdtales** [comment]
@HopefulLlama Here is another example project: https://github.com/db-migrate/api-examples

Also please note: The API specification is not yet finished and there are things that are going to be improved, such as using promises on this level and so on.
But from the very basic this is a very little example, hope this helps a bit.

**Comment by woraphol-j** [comment]
Hi @wzrdtales , thanks for your nice plugin.
However, I can confirm this bug. Your another example works fine as the index.js file that contains code to run migration programmatically resides at the project root level. However, if the file reside in nested folder, the same error as found by the OP will occurs. The error occurs at this line:

module.exports.getInstance = function(isModule, options, callback) {

  delete require.cache[require.resolve('./api.js')];
  delete require.cache[require.resolve('optimist')];
  var mod = require( './api.js' ); <----- This line causes error
  return new mod(isModule, options, callback);
};

This is the case in the framework like express or loopback where some boot script files reside in nested directories.

**Comment by wzrdtales** [comment]
Actually the line you highlight won't be an error in any case that I can mind of.

Please provide me with a reproducable case, for example setup a gist that verifyable throws your error and I will have a look at this. Currently I can just hardly guess what your problem is, as I have to less details.

Please also come always up with your used npm, node, db-migrate, db-migrate-driver version and post a verbose run where you see an error being throwed, in this case as this seems to be related to programatic access you can set a global variable named verbose to true which is going to be recognized by db-migrate.

**Comment by wzrdtales** [comment]
Also please use code blocks if posting code, I've just edited your issue to make it easier to read.

**Comment by wzrdtales** [comment]
@woraphol-j Any new news on this or did you resolved your issue?

**Comment by liammclennan** [comment]
Definitely still a problem. The exception is thrown from api.js:930 (beta.15). Which is:

```
function run(internals, config) {
  var action = internals.argv._.shift(),
    folder = action.split(':');
```

`argv._.` is an empty array, so `shift()` returns undefined, which does not have a `split()` method. Here is debug output showing the relevant values:

```
internals
Object
argv:Object
configFile:"db/database.json"
dbm:Object
dryRun:false
ignoreCompleted:false
matching:""
migrationOptions:Object
migrationTable:"migrations"
notransactions:false
```

**Comment by wzrdtales** [comment]
@liammclennan Coud you please elaborate what you're trying to do?

I ask as `run` you normally never call if you use db-migrate programatically. Run is actually the part of the API entering into the non programatic behavior.

**Comment by liammclennan** [comment]
Run () is what the doctor says to use. I'm trying to run migrations
programmatically.

On 20 Aug 2016 18:52, "Tobias Gurtzick" <notifications@github.com> wrote:

@liammclennan <https://github.com/liammclennan> Coud you please elaborate
what you're trying to do?

I ask as run you normally never call if you use db-migrate programatically.
Run is actually the part of the API entering into the non programatic
behavior.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/db-migrate/node-db-migrate/issues/345#issuecomment-241188085>,
or mute the thread

**Comment by wzrdtales** [comment]
yes, tbh docs aren't really final yet.

Have a look here: https://github.com/db-migrate/api-examples

There are a few examples, some in promise style and callback style, that should help understanding.

**Comment by devotis** [comment]
If you run your app using `npm run start`, you can add a prestart script to npm to do the migrations before your app starts. In package.json you would have:
```
{
  "scripts": {
    "prestart": "db-migrate up",
    "start": "node ./index"
  },
  ...
}
```
