### ISSUE TITLE
Scope:all using to upload seed data

### ISSUE THREAD

**Issue by noon-ehos** [db-migrate/node-db-migrate#357]
So I have some seed data migrations in subfolder "migrations/data" and want to apply this migrations with schema migrations from "migrations" folder.

What i need?
run migrate up:all (on some dev or test environment) and apply migrations from "migrations" and "migrations/data" folders ordered by timestamp in file names

For example: 
1. apply table1 schema from migrations
2. apply table1 seed data from migrations/data
3. apply table1 schema changes from migrations
4. apply table1 additional seed data from migrations/data

Current problem:
all migrations now applies from root folder "migrations" at first, than from each subfolder ordered desk by subfolders names.

So if i have an old schema with old seed data, I cant create schema changes on this table because when I will apply it on clear db, at first will be applied old schema and changes and than old seed data with expecting old schema. So i have errors.

Can we change it? or maybe I need some other workflow for this process?

**Comment by wzrdtales** [comment]
> Can we change it?

No, fixing a problem just for your special workflow and breaking everyone else migrations is not a solution. Let's look out how to solve it in a way that doesn't break anything.

To specify:
You do not use scopes how you should:

Every scope is independent to any other scope. Thus it **MUST** be executed apart from the other ones. So we go through every scope completely before switching to another scope. The way you try to work with scopes was never intended and thus wont work. The reason for this is that scopes have some special features, like changing the database system or just the database, tweaking the config for this specific scope.
All in all: Scopes are an organization tool, and are independent form other scopes. That is also why the are called scopes, because they are as long isolated and independent from all other migrations as you do not rely on them,

Things that are planned for scopes in the future are: 
- sorting of scopes (define the order of execution for `all` as an array or by specifying alphanumeric and other sorting schemes. 
- Connecting to other dbs
- More config tweaks

**Comment by noon-ehos** [comment]
thanks for reply, we will use scopes as isolated processes but will also will use some tweak for us.
we will create dev scope and master scope and create all migrations isolated for each scope but for similar migrations of schema we will use sql files from another sql folder and will include it to both scopes migrations. It gives us  ability to do all general changes in one place (sql file) and in the same time to have isolated migrations with seed data fro dev scope.

**Comment by jonathan-fulton** [comment]
@wzrdtales, I understand how you've constructed scopes to date.  Makes sense.

That being said, the seed data problem @noon-ehos explained above is one found in EVERY real project and the workflow isn't remotely "special".  I've used it numerous times.  Seed data should be thought of just like any other migration and has dependencies on the core migrations to date.  However, you only want to run seed data migrations on non-prod environments.  Thus to facilitate the most logical workflow for handling seed data, you need the ability to optionally run seed data migrations.  It'd be awesome if db-migrate could support this.

**Comment by wzrdtales** [comment]
@jonathan-fulton I know the cases where one needs special data, that is **NOT** used in production such as seeds for development, but scopes are not the solution to the problem. They're intended for a complete different purpose, but I understand that they seem to look like a solutoin as of db-migrate currently lacking functionality to cover this problem.
This is where I differentiate between seeds in a traditional sense (those kind of seeders which I most commonly call as just a more slow and complex alternative to sql files) and migrations themselves. Migrations as the name says do migrate some state from one to another, but they do not necessarily change any data nor do they insert any and if they do, you're starting again to mix two things that you should want to split.

To make it short for now, supporting this kind of feature is in work and I'm happy to see that you want to contribute. I'm always open to ideas, opinions and discussions so just let me know if you have questions and I will answer them. I also will try to describe the idea behind the concept (which you've already noticed in another issue) of the seeders, static and version controlled ones, that are going to be introduced in db-migrate and why they are designed like they are and how they operate **together** with migrations. I wanted to do that today, but I'm a bit to tired from the day right now, I will move that to tomorrow though. In the meanwhile, please feel free to ask questions, if you feel like it does not make sense to open an issue from some specific questions you can also drop me a mail (see my github profile), also I nearly always prefer issues as they are open to everyone to participate :)

**Comment by jonathan-fulton** [comment]
@wzrdtales thanks for this response as well :)
