### ISSUE TITLE
Breaking Change 0.10.0-beta.14

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [db-migrate/node-db-migrate#392]
This version (0.10.0-beta.14) introduced a backwards compatibility issue/breaking change with the api. We use db-migrate programmatically on app startup to run "up" migrations. It seems the jump from 0.10.0-beta.13 to 0.10.0-beta.14 has introduced a bug in the way the callback is defined/invoked. When callback was added to the bind call in the executeUp function, it shifted arguments. Therefore, contrary to documentation, this callback definition no longer works:

``` javascript
var apiStartCallback = function(migrator, originalError) {
    migrator.driver.close(function(err) {
        if(originalError) {
            logger.error("Database migration failed with original error:");
            logger.error(originalError);
            logger.error("API not started");
        } else if(err) {
            logger.error("Database migration failed:");
            logger.error(err);
            logger.error("API not started");
        } else {
            logger.info("Database migration complete");
            server = app.listen(app.get('port'), function() {
                logger.info('Express server listening on port ' + server.address().port);
                logger.info("Started API");
            });
        }
    });
};
```
##

**Comment by wzrdtales** [comment]
Hey @wbautistaEXPEDIA 

Thank you for reporting, those were the changes between those two versions.

Can you give me a fully working example that is reproducing what you experience?  I'm not exactly sure what you try to do though. What I can see is that you call `migrator.driver.close` which wouldn't be part of the official programable API though. May be you can put up a gist with everything in it?

**Comment by wzrdtales** [comment]
forgot the compare link https://github.com/db-migrate/node-db-migrate/compare/v0.10.0-beta.13...v0.10.0-beta.14

**Comment by wzrdtales** [comment]
Also see here for examples of the progamable API https://github.com/db-migrate/api-examples

**Comment by wbautistaEXPEDIA** [comment]
var App = require('./app');

### server.js
```javascript
/**
 * Starts the API. The API only starts if database migration was successful.
 *
 * @param migrator the database migrator
 * @param originalError an error that occurred during migration, or {@literal null} if one did not occur
 */
var apiStartCallback = function(migrator, originalError) {
    migrator.driver.close(function(err) {
        if(originalError) {
            logger.error("Database migration failed with original error:");
            logger.error(originalError);
            logger.error("API not started");
        } else if(err) {
            logger.error("Database migration failed:");
            logger.error(err);
            logger.error("API not started");
        } else {
            var app = App(context);
            logger.info("Database migration complete");
            server = app.listen(app.get('port'), function() {
                logger.info('Express server listening on port ' + server.address().port);
                logger.info("Started API");
            });
        }
    });
};

var schema = dbMigrate.getInstance(true, dbOptions, apiStartCallback);
logger.info("Running database migrations...");
schema.up();
```

The above code worked prior to 0.10.0-beta.14, as it was developed based on the [documentation](https://db-migrate.readthedocs.io/en/latest/API/programable/#using-db-migrate-as-module). After poking around in the api, I noticed that a callback was added in the executeUp function using bind(), and it appears to have shifted the callback args, thus breaking the existing code above.

**Comment by wzrdtales** [comment]
Ok, Ic where this behavior change comes from comes from

https://github.com/db-migrate/node-db-migrate/blob/master/api.js#L187-L190

We now return a callback before this db-migrate was only callback compatible, the callback is itself omitable. Through the changes made, a callback is now always being passed. But this is more a feature than a bug considering that there is principially no such thing as a synchronous version.

So this is just kind of a breaking change. Actually there is a thing that I don't like at all: the callback should always be the last param. For some strange reason this is not the case for the `oncomplete` callback. This is definitely going to change and I will change the order of those arguments to let the callback be only and really only the last argument.

However, your problem can be and should be fixed in another way though. I have posted you an example below, just let sayed that you currently kind of abuse the callback overwrite. This callback override is actually intended to execute some actions before finally closing the driver. You also did not respect the callback of the overridden callback, which actually led to your problem above, so you basically have intercepted a db-migrate function without properly handling the callback. 

What you want to do is intended to be done in a more, way easier way. Just look into the example of your modified code in how this would be done with a callback. You have since `0.10.0-beta.14` also now finally promises available, see this as an example: https://github.com/db-migrate/api-examples/blob/master/promise.js

Also worth mentioning is, that with `0.10.0-beta.14` all API functions were finalized and are marked as stable, thus the way they act wont change from now on anymore. Except for the overriden callback, that is going to change to be compliant and have the callback put at the end.

```javascript
var config = require('./config');
var App = require('./app');
var dbOptions = {
    cwd: "./schema",
    config: {
        defaultEnv: "current",
        current: {
            driver: "mysql",
            host: config.host,
            user: config.user,
            password: config.decryptedPassword,
            database: config.database
        }
    }
};

/**
 * Starts the API. The API only starts if database migration was successful.
 *
 * @param migrator the database migrator
 * @param originalError an error that occurred during migration, or {@literal null} if one did not occur
 */
var apiStartCallback = function(err) {

    if(err && err.originalErr) {
        console.error("Database migration failed with original error:");
        console.error(err.originalErr);
        console.error("API not started");
    } else if(err && err.err) {
        console.error("Database migration failed:");
        console.error(err.err);
        console.error("API not started");
    } else {
        console.log("Database migration complete");
    }
};

var schema = dbMigrate.getInstance(true, dbOptions);
logger.info("Running database migrations...");
schema.up(apiStartCallback);
```

So with the above you should be fine and it is also more straightforward, easy and readable though.


Hopes this helps you, if any issue, please don't hesitate and let me know :)

**Comment by wzrdtales** [comment]
Also adding, docs for all this stuff are in work and not quite there yet, if you want to help out and open a PR on the docs you would be welcome though :)

**Comment by wbautistaEXPEDIA** [comment]
Yes, thanks for pointing me in the right direction. I just wanted to make sure you were aware that there was a breaking change made, and that the documentation contradicts some of what you explained. We decided to use the promisified version of the API. Thanks.

**Comment by wzrdtales** [comment]
Yes, again thanks for reporting, I highly appreciate this :)
