### ISSUE TITLE
multi statements for psql / only work when using psql commandline client

### ISSUE THREAD

**Issue by User4martin** [db-migrate/node-db-migrate#426]
Using postgres, I am adding big stored procedures, I avoid putting sql and js into one file. 
So --sql-file is the option to go.

I used to put related updates into one file

ALTER TYPE foo ADD VALUE IF NOT EXISTS 'bar' AFTER 'xyz';
CREATE OR REPLACE FUNCTION abc()....

This works fine, if I pipe it into the psql cmd-line client. (I guess psql parses it, and submits individual statements, rather than one multi-statement.

With db-migrate, having such a file fails, as the alter type does not work in multi-statements. 

That of course is not an issue of db-migrate. But it means fragmenting my sql to more files.

Would it be considerable to add a connection that pipes into the psql client? (Or other ideas?)
##

**Comment by wzrdtales** [comment]
@User4martin First of all, I would suggest to raise this issue also on the pg driver used by db-migrates pg driver. https://github.com/brianc/node-postgres, maybe they have a solution for your problem.

So talking about the psql client, there is at least an existing wrapper here https://www.npmjs.com/package/psql-wrapper,but I wont include this into the pg driver. Rather I would create a new driver which is working with that wrapper instead of `pg`. You're always free to write your own driver though, but currently I also wont put my hands on a driver that works with the psql cli instead of a real library.

**Comment by wzrdtales** [comment]
To add, I wont currently, mostly b/c I don't have the time to do this.

**Comment by wzrdtales** [comment]
You might also want to test how it behaves if you use the native driver instead. You need to install the pg-native module, as well as specify the usage in your config with the option `native: true`.

**Comment by LukasBeaton** [comment]
multiple statements do not work in MySQL...this is a pretty BIG limitation

**Comment by wzrdtales** [comment]
@LukasBeaton How do you come to the conclusion they don't? They actually do.

**Comment by wzrdtales** [comment]
@LukasBeaton Did you read the docs? Maybe you just missed on this part here though: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/#important-for-mysql-users
