### ISSUE TITLE
Autoincrement ignored on changeColumn

### ISSUE THREAD

**Issue by benbotto** [db-migrate/node-db-migrate#429]
Changing a primary key column that has AUTO_INCREMENT set results in the AUTO_INCREMENT being removed.  Consider the following migration, wherein the userID is changed from signed to unsigned.  Prior to the migration, userID had AUTO_INCREMENT set.

```
'use strict';

exports.up = function(db) {
  return db.changeColumn('users', 'userID', {
    type         : 'int',
    autoIncrement: true, // Ignored.
    notNull      : true,
    unsigned     : true, // This is what's being modified.
  });
};

exports.down = function(db) {
  return db.changeColumn('users', 'userID', {
    type         : 'int',
    autoIncrement: true,
    notNull      : true,
    unsigned     : false,
  });
};
```
Here's the output:
```
$ node node_modules/db-migrate/bin/db-migrate up --migrations-dir ./api/db/migration --config ./api/db/migration/database.json --verbose
[INFO] Detected and using the projects local version of db-migrate. '/home/avejidah/programming/cea-exam/node_modules/db-migrate/index.js'
[INFO] Using dev settings: { driver: 'mysql',
  user: '[REDACTED]',
  password: '******',
  database: '[REDACTED]',
  multipleStatements: true }
[INFO] require: db-migrate-mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /home/avejidah/programming/cea-exam/api/db/migration
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20161016162435-add-auto-increment-to-userID
[SQL] SET AUTOCOMMIT=0;
[SQL] START TRANSACTION;
[SQL] ALTER TABLE `users` CHANGE COLUMN `userID` `userID` INTEGER  UNSIGNED NOT NULL
[SQL] INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20161016162435-add-auto-increment-to-userID',
    '2016-10-16 09:50:05' ] ]
[INFO] Processed migration 20161016162435-add-auto-increment-to-userID
[SQL] COMMIT;
[INFO] Done
```
Note the resulting ```CHANGE COLUMN``` statement does not have AUTO_INCREMENT.

Node version 6.6.0
npm version 3.10.8
db-migrate-0.10.0-beta.20
db-migrate-mysql-1.1.9

Thanks for the help.

**Comment by wzrdtales** [comment]
@benbotto Hey,

This is due to the way how this is currently implemented:
https://github.com/db-migrate/mysql/blob/master/index.js#L110

It omits those, if there is no `unique` spec or `primaryKey` spec. This makes sense as MySQL only allows AI on columns with one of those indexes, but the current implementation it is problematic as I can see from your example. That would mean that one can't add AI to a column without removing the primaryKey or unique key to recreate it afterwards. I will change this behavior to not silently omit auto increment, as it would make sense to omit in some cases it on the one hand, but is unexpected on the other hand.

Thanks for reporting!

**Comment by wzrdtales** [comment]
published as

+ db-migrate-mysql@1.1.10

**Comment by benbotto** [comment]
Thank you for the prompt fix!
