### ISSUE TITLE
"Latest" docs show `callback` arg to `up()` but `db-migrate create` does not

### ISSUE THREAD

**Issue by chadfurman** [db-migrate/node-db-migrate#439]
Creating a migration with `db-migrate create` yields `up (db)` rather than `up (db, callback)` -- this is inconsistent with the docs.

I'm running 0.10.0-beta.20 from NPM

**Comment by wzrdtales** [comment]
@chadfurman This true, but not entirely.

Both versions are equally correct. While `up (db, callback)` is more considered of an old fashioned way to write migrations, `up (db)` is the new and preferred one.

The first one is the traditional callback style, the second one is utilizing promises. So instead of calling a callback, you return a valid handled promise instead.

So true is, that this is yet missing from the docs and some examples still only represent the callback style, due to being updated currently. Not entriely true is that it would be inconsistent as both ways are valid ways to write your migrations while I agree that this is currently a bit confusing that there are different results from what is presented in the docs. If you want you can go ahead and create a PR extending this part of the docs already :). PRs are always very much appreciated though.

**Comment by chadfurman** [comment]
@wzrdtales I'd create a PR if I understood it.  How does the new promise-style work?  My migration simply returns null.  What are other possible return values?

**Comment by wzrdtales** [comment]
@chadfurman Well actually promises. `return null;` would be equal to `return Promise.resolve();` though.

Every API of db-migrate on the 0.10.x tree by date does in fact return a promise though. Which you can just straightforward return.

To understand Promises, you can have a read here:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

DB-Migrate itself uses bluebird, which also extends Promises with some features. You can read about that one here:
bluebirdjs.com/docs/api-reference.html

An example of a valid `Promise` style migration can be found in the example project over here:
https://github.com/db-migrate/api-examples/blob/master/migrations/20160127220809-my-api-table.js

A valid way to chain commands in Promises, is just the normal way that is valid for Promises in general.

To give an example with the db-migrate api:

```
exports.down = function(db) {

  return db.dropTable('test')
  .then( () => db.dropTable('test2') );
};  
```

**Comment by chadfurman** [comment]
@wzrdtales how'd I do?  <3

**Comment by wzrdtales** [comment]
Cool thing! Gonna have a look later
