### ISSUE TITLE
Support for multiple statements when using external SQL file

### ISSUE THREAD

**Issue by Wildhoney** [db-migrate/node-db-migrate#505]
I've setup my `database.json` &mdash; which is definitely being used &mdash; to specify `multipleStatements: true`:

```json
{
    "mysql": {
        "ENV": "DB_CREDENTIALS",
        "multipleStatements": true,
        "native": true
    }
}
```

However, when I try to migrate the following SQL migration &mdash; which was created by using `db-migrate create add-quotes --sql-file -e mysql` &mdash; I get an error that suggests multiple statements aren't supported when using `--sql-file`:

```mysql
CREATE TABLE `cocktails` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `slug` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `date_added` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `quotes` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `quote` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

Which produces the following error:

> Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that
> corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE
> `quotes` (
> `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
> `quot' at line 10

**Comment by wzrdtales** [comment]
No worries, stale bot was just activated, it automatically stales and closes issues though. When something is not solved just react to it. Concerning to your example, I will try to reproduce this.

**Comment by Wildhoney** [comment]
Thanks @wzrdtales &ndash; the `multipleStatements ` doesn't *appear* to be applicable to external SQL files.

**Comment by Wildhoney** [comment]
Did you manage to reproduce @wzrdtales?

**Comment by captainamerican** [comment]
If you're using the DATABASE_URL environmental variable, you can bypass this bug in the following manner:

`mysql://user:pass@host/database?multipleStatements=true`

I'm don't why this works. It was a last ditch effort before I got rid of db-migrate.

**Comment by wzrdtales** [comment]
Thanks for answering this @captainamerican <3

However, that is not a bug, this is the predefined behavior of the mysql driver (not the db-migrate driver but the low level driver).

And this works because `?` parameters are interpreted for first level arguments and `multipleStatements` results from this: 
https://github.com/mysqljs/mysql#multiple-statement-queries

I thought about changing the driver (db-migrate level) to use mutliple-statements by default, but did not yet had time to check if this has sideeffects or even breaking changes implied.

**Comment by bhubr** [comment]
Just throwing my two cents in. `db-migrate` is really great, but apart from deciding if `multipleStatements` should be made a default, there is definitely, IMHO, a **documentation** issue.

The [usage](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/usage/) page mentions the `--sql-file`, and states that "the sql files will have the following content:"

    /* Replace with your SQL commands */

Now, correct me if I'm wrong, but `SQL commands` seems to imply that you may put several of them, which I incorrectly assumed. So I lost a fair amount of time trying to fix an SQL schema that wasn't broken, just because I got the exact same error as the OP when trying to import a schema.

It might be worth mentioning, in the auto-generated SQL files, that issuing multiple statements without specifying multipleStatements will result in errors!
