### ISSUE TITLE
[Feature Request / Bug] Don't process.exit(1) in the API; Throw an error instead

### ISSUE THREAD

**Issue by Flaque** [db-migrate/node-db-migrate#516]
_Disclaimer: I may be totally off base on what's actually happening here, if I am please let me know_ 😅

## Overview 
The API shouldn't quit the process, it should throw an error so that clients can catch the issue.

## Issue
When the API fails, it sometimes throws a `process.exit(1)` which can lead testing frameworks (Jest) to misplace blame. Since Jest (and Ava) run tests in parallel, `process.exit(1)` can stop the whole shebang in the middle of something leading to weird errors like this:

![Screenshot of error](https://user-images.githubusercontent.com/5942769/32924244-83ca53a0-caf0-11e7-8938-36f2535319a5.png)

For Screenreaders:
```
PASS src/lib/frame/test/frame.test.js
RUNS src/lib/core/test/core.test.js
error Command failed with exit code 1.
```

In the example above, a test that hadn't reported in yet may have called the `process.exit(1)`, but since that interrupted the output of `src/lib/core/test/core.test.js`, it appears as if that test is the cause.

At the moment, it looks like the `api.js` node-db-migrate is calling the commands directly via `load`. 

Take the `create` command, as reproduced below:

``` js 
create: function (migrationName, scope, callback) {
    var executeCreateMigration = load('create-migration');  // This right here being loaded in
    // ... Other stuff
},
``` 

That will call the `lib/commands/create-migration.js` file, which calls `process.exit(1)` in several places. For example, if it fails to create a migration:

``` js
  createMigrationDir(migrationsDir, function (err) {
    var index = require('../../connect');
    var Migration = require('../migration.js');

    if (err) {
      log.error('Failed to create migration directory at ', migrationsDir, err);
      process.exit(1);
    }

    // ...
  }
```

## Solution

Whenever we would call `process.exit(1)`, check if we're running in the API and instead throw an error? Or maybe redefine `process.exit` to something like this:
``` js 
const oldProcessExit = process.exit;

// Before API defs
process.exit = (code) => {
  throw new Error(`Something went wrong in db-migrate! Error code: ${code}`); 
}

// After API defs
process.exit = oldProcessExit;
```

--- 

If this is okay, I would be willing to take a stab at it. If not, no worries.

**Comment by wzrdtales** [comment]
No need to fix. Just tell db-migrate to not register the events on uncatched{Rejection,Exception}.

The options property you need to set for this is, `throwUncatched`, see also here:

https://github.com/db-migrate/node-db-migrate/blob/4de822b8d420148f1c661de9f816585831bc5f84/api.js#L42

**Comment by wzrdtales** [comment]
Ah and I just saw the createMIgrationsDir example, that should be probably just removed though.

**Comment by Flaque** [comment]
Thanks so much! ❤️

I added a PR to the docs to add this option. (If that was the wrong place, let me know). Thanks for the help!

**Comment by wzrdtales** [comment]
My pleasure, and thank you for contributing on the docs <3

I will also push out a change to replace the aforementioned exit.

**Comment by Flaque** [comment]
<3

**Comment by artemave** [comment]
Hats off to @Flaque's diplomacy skills. I, on the other hand, am pretty speechless.

Because I just spent a number of minutes figuring as to why the following code

```javascript
(async () => {
  const dbmigrate = require('db-migrate')

  process.env.DATABASE_URL = 'postgres://localhost:5432'

  const dbm = dbmigrate.getInstance(true)
  await dbm.dropDatabase('pr-apps-test')
  await dbm.createDatabase('pr-apps-test')
  await dbm.up()
})().catch(e => {
  console.error(e)
})
```

Ends up with
![image](https://user-images.githubusercontent.com/23721/36636641-75364af8-19c2-11e8-96ce-d3b88149cf8d.png)

And what do I find in the end? `process.exit(1)` inside a _library_ code.

**Comment by Flaque** [comment]
:'( Sorry you ran into that @artemave. Glad you found the issue though!

**Comment by wzrdtales** [comment]
@artemave db-migrate is not a library, but lately **also** a library ;) So for programmatic modes, it could happen that some stuff should not be where it is. I am not sure though, what you wanted to reach with your comment here. Which is not a bug report, nor a feature suggestion, nor you seem to want to help out or something. It feels more like you just wanted to brag around here, I am sorry if you did not wanted to, but this clearly reads like it. I want to friendliest point yout to the [COC](https://github.com/db-migrate/node-db-migrate/blob/master/CODE_OF_CONDUCT.md).

So did you ran into the issue of public registers right? Can't say since you did not provided a proper problem description. However, when @Flaque opened this issue, I'm not quite sure if I respected the programmatic mode at that time, I agree however, that for that mode we should default to not register the error handlers.

**Comment by artemave** [comment]
A library must not:

- call `process.exit`
- call `console.log`

This library does both and that is about the most accurate description of the problem that I can come up with.

**Comment by wzrdtales** [comment]
@artemave DB-Migrate was once just a cli tool and now started to provide abilities to be used as a module. You're doing nothing more than wasting time, if you want to actually help the open source community, be constructive and helpful. Yes bugs existss, problems exist and all is fine. But I see I was right, you do want only brag around here, and with that I kindly again refer you to the [COC](https://github.com/db-migrate/node-db-migrate/blob/master/CODE_OF_CONDUCT.md).

I am more than happy to accept bug reports from you, or even better, see you actually helping the open source world and contributing PRs, which would be awesome!

After all this is open source, and we, the whole community and I really mean no single other open source project of the world is due anyone anthing.

Since I do not waste time on trolling or toxicity too much, this will not receive any subsequent answer, since the topic is cleared up and intentions are clear since the only thing you still do is brag around, even though I started an actual dialogue about what could be improved. This behaviour is not welcome and is not tolerated, you're still welcome to participate, but in a way that is not just profiling yourself and in a way that is constructive.

Thanks for understanding.
