### ISSUE TITLE
How to create seeders for migrations?

### ISSUE THREAD

**Issue by CatDidenko** [db-migrate/node-db-migrate#598]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior
Plaese, add example how to create and use seeders for migrations.

**Comment by CelineBen** [comment]
We have also been looking for documentation on how to get seeders to work.
Would someone more familiar with them be able to point us in the right direction?

Thanks !

**Comment by jhnferraris** [comment]
Any documentation for seeders?

**Comment by mgmgpyaesonewin** [comment]
+1 on seeder for migrations.

**Comment by valecarlos** [comment]
+1

**Comment by sulaiman1073** [comment]
+1

**Comment by richardsimko** [comment]
2 years later. Any time now... 😂

**Comment by wzrdtales** [comment]
seeders have never been a priority in any of the projects i worked in. otherwise it would have been long time done^^ It is simple I know what and how to do it, but the time for it also needs to be there. There always some magical windows where I just push out some substantial amounts of code here, but reality shows I get entangled here and there around the world and time gets passed by. Which doesn't mean I don't want to, I just have to focus at certain times at certain things :)
