### ISSUE TITLE
db.insert() doesn't work

### ISSUE THREAD

**Issue by AndrewRayCode** [db-migrate/node-db-migrate#606]
## I'm submitting a...

 - [ x ] Bug report  

## Current behavior
According to the docs:

> insert(tableName, columnNameArray, valueArray, callback)

However,

```javascript
      return db.insert(
        'table',
        ['col1', 'col2'],
        ['data1', 'data2']
      );
```

```
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: callback is not a function
    at /root/.npm/_npx/1/lib/node_modules/db-migrate/lib/commands/on-complete.js:15:14
```

OSX
Postgres
` "db-migrate-pg": "^0.4.0"`

**Comment by rgrwkmn** [comment]
If you add a callback function as the fourth argument it will work. It seems this method wasn't updated to work correctly with the promise changes. If @wzrdtales is still active I'll submit a pull request to fix this. Otherwise I will either fork this repo to make my fixes or give up and look for a project that is being maintained.

**Comment by wzrdtales** [comment]
Feel free to submit a PR :)

**Comment by rgrwkmn** [comment]
https://github.com/db-migrate/db-migrate-base/pull/13
