### ISSUE TITLE
Question: database.js vs database.json

### ISSUE THREAD

**Issue by danielb2** [db-migrate/node-db-migrate#611]
## I'm submitting a...

 - [ ] Bug report  
 - [x] Feature request
 - [ ] Question

I'm using confidence, which is a loader for environments.  The configuration is thus not compatible with having a database.json file.

Has it been considered to also check the paths for a database.js file ? If a js file was to be accepted then it's easy enough to do things to programmatically export what db-migrate expects.

**Comment by iamvanja** [comment]
Just stumbled upon this as I wanted to cast string `'true'` to boolean `true` so needed a JS file.
Not sure if you are aware, but you can specify custom config file `db-migrate --config 'server/database.js'`. As long as you `module.exports` JSON content you should be fine.

**Comment by danielb2** [comment]
thank you!

**Comment by danielb2** [comment]
it would still be nice if it accepted database.js without having to specify --config so I'll leave it open

**Comment by wzrdtales** [comment]
I retagged this as feature request as of for now, since there are open questions to this. It is most likely this will not be implemented since this will have crucially dangerous side effects. Changing the behavior in this case, will import a `database.js` file, which might actually exist in the projects of db-migrates user. Therefor this could and will have unknown side effects, I will keep this open for a while and review it again, to decide what to do with this. Clear is only one thing: This will not be a feature by default. Options are however: A plugin to add support for that or configuring it via the `rc` config.

**Comment by wzrdtales** [comment]
Also to add, in your use case you might rather want to use the programable interface instead.

**Comment by danielb2** [comment]
since it's already available via `--config` it would be nice to have an option to not have to specify it each time

**Comment by wzrdtales** [comment]
@danielb2 Not happening, since this would be an alteration that would end up in an expected behavior for users using db-migrate for a while. This could have horrible side effects and could destroy complete production environments. Since db-migrate is being used in a lot of big production projects already, I will never allow any modification to core behavior. However this could be accomplished by plugins or a rc config.

**Comment by danielb2** [comment]
It actually works in the `rc` like I'd hoped. I played with it a bit more this morning. I've been on the road and it's for a side project. Since it does what I need, I will close this. Thanks so much for taking the time to respond.
