### ISSUE TITLE
Execution fails when bundled with WebPack due to dependency on PkgInfo

### ISSUE THREAD

**Issue by BrycePC** [db-migrate/node-db-migrate#621]
## I'm submitting a...

 - [x ] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
I am attempting to test a new project with db-migrate, which has been bundled using webpack for deployments/execution on AWS Lambda. The current error is reported when attempting to run the migration:

START RequestId: 720ed4a8-7a75-48b4-8c03-66bf12bea426 Version: $LATEST
module initialization error: Error
    at Function.module.exports../node_modules/pkginfo/lib/pkginfo.js.pkginfo.find (/var/task/index.js:8651:11)
    at Function.module.exports../node_modules/pkginfo/lib/pkginfo.js.pkginfo.find (/var/task/index.js:8663:18)
    at Function.module.exports../node_modules/pkginfo/lib/pkginfo.js.pkginfo.find (/var/task/index.js:8663:18)
    at Function.module.exports../node_modules/pkginfo/lib/pkginfo.js.pkginfo.read (/var/task/index.js:8676:22)
    at module.exports../node_modules/pkginfo/lib/pkginfo.js.module.exports (/var/task/index.js:8625:21)
    at Object.<anonymous> (/var/task/index.js:8683:1)
    at Object../node_modules/pkginfo/lib/pkginfo.js (/var/task/index.js:8688:30)
    at __webpack_require__ (/var/task/index.js:21:30)
    at Object.<anonymous> (/var/task/index.js:7263:47)
    at Object../node_modules/db-migrate/index.js (/var/task/index.js:7328:30)
END RequestId: 720ed4a8-7a75-48b4-8c03-66bf12bea426
REPORT RequestId: 720ed4a8-7a75-48b4-8c03-66bf12bea426	Duration: 247.46 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 55 MB	
module initialization error
Error

I have noted others have reported similar issues with PkgInfo with webpack; the resolution has been the removal of PkgInfo dependency by component authors.

## Expected behavior
DbMigrations should run 'up' as expected. This runs ok when webpack is not used (webpack is part of our organisation's standard devops process to reduce bundle sizes).

## Minimal reproduction of the problem with instructions
Run db-migrate project following a build with webpack/commonjs2.

## Environment

<pre><code>
db-migrate version: 0.11.5
plugins with versions: X.Y.Z
db-migrate driver with versions: db-migrate-mysql": "^1.1.10"

Additional information:
- Node version: XX  
- Platform:  Linux/AW Lambda

Others:

</code></pre>

**Comment by maslakov** [comment]
Have the same issue. As workaround have to pack now everything with node_modules into zip archive to run on AWS-lambda

**Comment by wzrdtales** [comment]
Can you be more explicit about the problem? Why is webpack failing? And why are you using webpack for a non browser environment?

**Comment by maslakov** [comment]
I cannot provide now an error no, because we gave up trying to pack stuff with webpack and just zip now everithing together with node_modules. But when I was trying to pack I was getting a warning about the usage of `require('pkginfo')(module, 'version')`. And then packed version was not usable.

Why? We wanted to have single js file to be used for lambda function. This works for us pretty good in more or less all our cases. This allows us to use single JS file as lambda instead of zip artifact.

In case of AWS lambda, migrations can be stored in S3 bucket, then lambda downloads them and puts in migration folder and then executes.

**Comment by BrycePC** [comment]
> Can you be more explicit about the problem? Why is webpack failing? And why are you using webpack for a non browser environment?

Use of Webpack is a standard devops process within our organisation for deploying AWS lambda functions; as a means of reducing footprint for deployments (eg 164kb in contrast to ~5GB). 
Using webpack also for backend is fairly-well described as a valid methodology especially for size and consistent bundling methods (eg https://www.npmjs.com/package/webpack, https://jlongster.com/Backend-Apps-with-Webpack--Part-I).

I have been able to workaround the issue using node pack (with 5GB deployable), but it is making our builds non-standard (and will restrict us from adopting db-migrate for other projects within the org).

**Comment by wzrdtales** [comment]
Well I am open for PRs though. If you want to help out on that point, you can give it a shot.

Currently pkginfo is only used to extract the version information, which could be retrieved by requiring package.json directly. So it wouldn't hurt too much to replace it with that. However, since I don't know why webpack is failing here and I will not test for any and every possible system, I ask for your help, since you're the users with that kind of problem and you have a working test setup available already. If you can figure out why webpack is failing and put out a PR that is not breaking and altering any of the current behavior, I will be happy to merge :)

**Comment by anshul07** [comment]
hi @wzrdtales, I have raised the PR to remove pkgInfo dependency. Can you please review it? Thanks
