### ISSUE TITLE
Any plan to support node ESM?

### ISSUE THREAD

**Issue by cj1128** [db-migrate/node-db-migrate#721]
## I'm submitting a...

 - [ ] Bug report  
 - [x] Feature request
 - [ ] Question

## Current behavior
The default generated migrations are all CJS files and can not be used in a ESM node project (`type="module"` in package.json).

It seems that node-db-migrate hardcoded the `.js` suffix. If I change the migration files extension to `.cjs`, it can't recognize them at all.

## Expected behavior
Provide an option to generate ESM migration code or recognize `.cjs` migration files.

## Environment

<pre><code>
db-migrate version: 1.0.0-beat.14
plugins with versions: none
db-migrate driver with versions: sqlite3 0.4.0

Additional information:
- Node version: 15.5.0
- Platform:  Mac

**Comment by wzrdtales** [comment]
not sure what you're hoping here for. you're never loading the migrations yourself. db-migrate does, so it would only matter that if you want to use db-migrate programatically, to access it it like that. Can you elaborate your use case more, what and why do you need that?

**Comment by wzrdtales** [comment]
however custom migration parsers are target for plugins for long time already. so you could just write a plugin to enable that. See the coffee script plugin as an example https://github.com/db-migrate/plugin-coffee

**Comment by cj1128** [comment]
I am sorry to be ambiguous, let me clarify this.

I have a project, and I set it up to be an ESM project, that is the `type` field in package.json is `module`.

I use the `migrations` directory the store the auto-generated migration files.

When I do the migration, I got this error:

```
[ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/cj/Documents/Work/pdb-api/migrations/20210110045153-init.js
require() of ES modules is not supported.
require() of /Users/cj/Documents/Work/pdb-api/migrations/20210110045153-init.js from /Users/cj/Documents/Work/pdb-api/node_modules/db-migrate/lib/file.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename 20210110045153-init.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/cj/Documents/Work/pdb-api/package.json.
```

The reason is that node-db-migrate is trying to `require` the migration file but the file is considered to be an ESM module (due to the `type` filed in the root package.json file). Obviously, one can't load an ESM module using `require`.

Back then I was busy writing the code so I didn't give too much time to think about it but filed this issue.

For future references, there are several ways to solve this problem without any modification of node-db-migrate.

1. Create a `package.json` file in the `migrations` directory and set its `type` filed to be anything except `module`. This is probably the easiest way.
2. Remove `type="module"` in root package.json and manually change all file extensions of our code from `.js` to `.mjs`.

**Comment by joeldenning** [comment]
I also ran into this - thanks for the workarounds suggested here. I think it would be best if db-migrate would call `import()` instead of `require()` when loading migration files, since `import()` works for both ES and CJS modules

**Comment by wzrdtales** [comment]
no best is backwards compatibility, when versions of node without support become old enough it will be considered

**Comment by joeldenning** [comment]
It seems you're against the feature, which is okay, but one thing to note is that it's very possible to implement it in a backwards compatible way. The mocha and jest libraries have done so by try/catching the `require()`, checking the error, and doing `import()` only if it's `ERR_REQUIRE_ESM`.

See https://github.com/mochajs/mocha/blob/9878f32a5a5394f100834aa26bb52144e07d7374/lib/esm-utils.js#L33 and https://github.com/facebook/jest/blob/f9132f9106e3f1b3ae6f81d1f36222055c3fe111/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L41-L46, which show this.

**Comment by wzrdtales** [comment]
well honestly. i don't care, it doesn't provide any benefit and I don't use it anywhere that might be true. But I don't care, the difference between me the maintainer and you the user is: I have responsibility. And that is backwards compatibility. Native es modules, and with that "import", in node "just" arrived and your example you're providing shows you didn't understand the problem. This is about backwards compatibility. Just introducing the work import anywhere in the code will break it for thousands of users, with not benefit at all for them (nor anyone else es modules really have no real benefit over require (at least if you know what you are  doing).

And before the question comes up to introduce a transpiler to the project such as babel. The answer is no, there is no use other than being incapable of waiting until maturity for using babel. It just introduces latency while the development effectively destroying flow and productivity.


So a small simple comprehension here: There will be absolutely no support for "import" and es modules in db-migrate until not 99% of all users dropped node v12 and upgraded.

**Comment by joeldenning** [comment]
> Just introducing the word import anywhere in the code will break it for thousands of users

Adding an unused `import()` does not throw an error in any LTS versions of NodeJS, starting with Node 10. Does db-migrate support node@9? That's the latest version of Node that throws an error when it sees a dynamic `import()` in a file. I see that the package.json says that node >= 8 is supported on the master branch for version 1.0.0-beta.14 - if that's true then yes it would be a breaking change.

> wouldn't mind to introduce it if it brings any benefit

The main benefit I see is not throwing errors when users have set `"type": "module"` in their package.json. "Don't use ES Modules" is an arbitrary and unnecessary restriction to place on users.

#### Alternative solution

Another solution would be to generate migration js files with the `.cjs` extension when inside of a package that has `"type": "module"`, and then have db-migrate look for either `.js` or `.cjs` when calling `require()`. This solution would work in Node 8 as far as I know, so it could be a good solution if backwards compatibility with Node 8 is needed.

**Comment by wzrdtales** [comment]
node 8 is still supported (the breaking changes label announces also node breaks). While node 8 can be dropped the support by now, it is now one year after the end of the lts period, most users and even most slow enterprises will have managed to update it, the support for import and es modules was not there until node 13.

however db-migrate wont use es modules internally anywhere soon, if ever since there is nothing wrong with require, but definitely not before 2023, due to backwards compatibility though. 

such problems are usually also moved out of db-migrates core into plugins, however the file loading itself is not yet available as a hook, it is simply done here this way https://github.com/db-migrate/node-db-migrate/blob/41ab6717f4d27be104c7c9084390400c3fba5304/lib/file.js#L84

The easiest solution however would be to

> Create a package.json file in the migrations directory and set its type filed to be anything except module. This is probably the easiest way.

Which @cj1128 wrote and maybe do that by default through db-migrate itself. Or add a plugin to register the cjs extension. All in all what the node developer team did here with the module system change is a mess, done quite ugly without really a good reason but complying to a standard module system. While I understand the movement, the execution is poor, if not terrible. In my opinion `"type": "module"` is a failure nothing more. However, this is not about my opinion. If there is a solution that neither needs a lot of maintenance, nor breaks any version until node 8 I would be fine with it, as long as I don't have to invest my own time on it.

**Comment by joeldenning** [comment]
> however db-migrate wont use es modules internally anywhere soon, if ever since there is nothing wrong with require, but definitely not before 2023, due to backwards compatibility though.

There's no need to refactor db-migrate to be in ESM. I think there's been some miscommunication here - I have not suggested using babel, nor rewriting db-migrate to use ES Modules, nor making a breaking change. My proposal is to keep db-migrate written in CJS, but to be compatible with projects using db-migrate that are written in ESM. The pull request for each of the solutions I suggested would be ~50 lines of code and not change any tooling/compilation for db-migrate - it would not be a rewrite. I agree that CJS works great and there's no need to engage in a huge refactor of db-migrate.

My hope is for db-migrate to be usable by projects whose package.json has `"type": "module"`. To accomplish that, I think the "Alternate solution" I proposed above is the least invasive approach. To summarize it:

1. `db-migrate create` checks if the package.json nearest to the `migrations` directory has `"type": "module"`. If so, db-migrate creates `<timestamp>-<name>.cjs` instead of `<timestamp>-<name>.js` files. The generated contents of the file are completely unchanged.
2. `db-migrate up` and `db-migrate down` call `require()` on `migrations/<timestamp-<name>.js` OR `migrations/<timestamp>-<name>.cjs` - whichever one can be loaded. This way, it can keep using `require()` and doesn't have to switch to `import()`

**Comment by joeldenning** [comment]
One other option that occurred to me, that might be even less invasive:

`db-migrate create` creates a `migrations/package.json` file whose contents are `{"type": "commonjs"}`, if that file doesn't exist. This is just putting @cj1128's excellent solution into db-migrate itself, so that other users don't encounter the error and have to come to this github issue to find a workaround.

**Comment by wzrdtales** [comment]
would be fine with that, since that would be the better solution, the first suggestion would suffer from scenarios where users switched to this configuration during the process and there are already js migrations that are in the worst case already executed in **production**, db-migrate already reads the package.json for installed plugins. feel free to shoot me a PR.

**Comment by joeldenning** [comment]
👍🏿  I've created #724 which addresses this for the 1.x beta versions.
