### ISSUE TITLE
Put M1 incompatibility in the readme please

### ISSUE THREAD

**Issue by masterprompt** [db-migrate/node-db-migrate#800]
Saw the other issue about lack of M1 compatibility.  Saying "you're screwed due to your hardware choice" is becoming less of an issue as intel will slowly be phased out of Apple world AND when we get new macs in the corp environments they are shipping M1s (and now M2s)..  So if we need to avoid your package, that's fine.  At least give us a heads up to avoid you right on the front page.  Please and thank you.

**Comment by wzrdtales** [comment]
Again someone who thinks open source is a free wish place where you can demand everything without giving anything back. If you need the support again: Push a PR for it. I wont do it for you, I don't have a Mac and will never have. So if you wish for that feature, do it yourself, its that easy and will be accepted as a PR if it fulfills the requirements and doesn't break anything.

**Comment by wzrdtales** [comment]
And again, just b/c apple arrogantly states: "Well developers will have to adjust after us.", it doesn't all will, actually most wont. You opted for special hardware, then you will have to do your fair share to get it supported, not the other way around.

**Comment by masterprompt** [comment]
Asking for accurate documentation isn't the same as asking for a feature, or a bug fix...  Also, get over yourself...  This is why you're still <v1.0, this is why no one is sponsoring you..  This is why many will avoid your library, and ultimately anything you touch..

**Comment by wzrdtales** [comment]
you started the tone, you get what you seed. This library is mostly funded by the projects that use it. Again you want something, then do it yourself. I will never put a banner here in front stating: mac users please piss off. And neither will you get your special treatment. I will not state as well this is incompatible with eventually powerpc or other architectures as well. 

You're not willing to open a PR and participate on your own to open source, fine, it will stay as it is, but that is on you if you decide to change it and make it compatible.

Bye, then, still invited to do the right thing and open a PR fixing the issue without breaking anything, otherwise have a nice day.
